spring:
  datasource:
    username: sanity
    password: wordpass
    url: jdbc:postgresql://postgres:5432/online-shop
  data:
    redis:
      host: redis
      port: 6379
application:
  security:
    jwt:
      secret: superSecret2004
