server:
  port: 8003
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
spring:
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
application:
  security:
    jwt:
      expirationMin: 30
      expirationDays: 15