version: '3.9'
services:

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: order-service/Dockerfile
    expose:
      - 8080
#    ports:
#      - "8080:8080"
    networks:
      - adapters-network

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: user-service/Dockerfile
    expose:
      - 8002
#    ports:
#      - "8002:8002"
    networks:
      - adapters-network

  mail-service:
    container_name: mail-service
    build:
      context: .
      dockerfile: mail-service/Dockerfile
    expose:
      - 8081
#    ports:
#      - "8081:8081"
    networks:
      - adapters-network

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    expose:
      - 8003
#    ports:
#      - "8003:8003"
    networks:
      - adapters-network

  role-service:
    container_name: role-service
    build:
      context: .
      dockerfile: role-service/Dockerfile
    expose:
      - 8004
#    ports:
#      - "8004:8004"
    networks:
      - adapters-network

networks:
  adapters-network:
    external: true
    name: adapters-network

