version: '3.9'
services:
  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_DB: online-shop
      POSTGRES_USER: sanity
      POSTGRES_PASSWORD: wordpass
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
#      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d

