version: '3.9'
services:

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - adapters-network

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - adapters-network

  mail-service:
    container_name: mail-service
    build:
      context: .
      dockerfile: mail-service/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - adapters-network

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8003:8003"
    networks:
      - adapters-network

networks:
  adapters-network:
    external: true
    name: adapters-network

