server:
  port: 8081
spring:
  profiles:
    active: secrets
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/online-shop
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
  thymeleaf:
    prefix: classpath:/templates/mail
    cache: false
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
application:
  rabbit:
    order:
      topic-exchange: Orders.Top
      fanout-exchange: Orders.FA
      queue: mail
      routing-created-event: Order.CreateMail
  web:
    order:
      base-url: http://localhost:8080/api/v1
      endpoints:
        product-images: /product/images
