version: '3.9'
services:

  postgres:
    image: postgres:latest
    container_name: adapter.postgres
    restart: on-failure
    environment:
      POSTGRES_DB: online-shop
      POSTGRES_USER: sanity
      POSTGRES_PASSWORD: wordpass
    expose:
      - "5432"
    ports:
      - "127.0.0.1:15432:5432"
    networks:
      - adapters-network
    volumes:
      - order.postgres.data:/var/lib/postgresql/users:rw
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: adapter.rabbitmq
    networks:
      - adapters-network
    expose:
      - "5672"
      - "15672"
    volumes:
      - order.rabbitmq.data:/var/lib/rabbitmq/:rw
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics check_running -q" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s

  redis:
    container_name: adapter.redis
    image: redis:alpine
    command: redis-server
    networks:
      - adapters-network
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - order.redis.data:/data
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  minio:
    container_name: adapter.minio
    image: quay.io/minio/minio:latest
    hostname: minio
    command: server --address ":9000" --console-address ":9001" /data
    networks:
      - adapters-network
    expose:
      - 9000
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=Q3AM3UQ867SPQQA43P2F
      - MINIO_ROOT_PASSWORD=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      - MINIO_SERVER_URL=http://localhost:9000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - data:/data

  proxy:
    build:
      context: proxy
    restart: on-failure
    networks:
      - adapters-network
    volumes:
      - ./proxy/config/conf.d/:/etc/nginx/conf.d/
      - ./proxy/config/html/:/usr/share/nginx/html/
#      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  order.postgres.data: { }
  order.rabbitmq.data: { }
  order.redis.data: { }
  data: { }

networks:
  adapters-network:
    driver: bridge
    name: adapters-network