server:
  port: 8004
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
spring:
  profiles:
    active: secrets
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/online-shop
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG