spring:
  datasource:
    username: sanity
    password: wordpass
    url: jdbc:postgresql://postgres:5432/online-shop
  rabbitmq:
    password: admin
    username: admin
    host: rabbitmq
  data:
    redis:
      host: redis
application:
  minio:
    host: minio
    access-key: Q3AM3UQ867SPQQA43P2F
    secret-key: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
